name: Build Go-Proxy-BingAI
on:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'release') }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Build Frontend
        run: |
          rm -r web/* && git checkout web/web.go
          cd frontend
          npm install
          npm run build
          cd ..

      - name: Commit latest webFile
        run: |
          rm -rf frontend/package-lock.json
          git config --global user.email "htmambo@gmail.com"
          git config --global user.name "htmambo"
          git add web/*
          git commit -m "[Upgrade] 🚀 Upload latest webFile" || true
          git push

      - name: Build binary
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -tags netgo -trimpath -o go-proxy-bingai main.go && tar -zcvf go-proxy-bingai-linux-amd64.tar.gz go-proxy-bingai
          cp go-proxy-bingai web

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: web
          retention-days: 3
